server {                           # This defines how Nginx should handle incoming HTTP requests for our application.
    listen 80;                     # Application inside container listen to port 80.
    server_name _;                 # The _ is commonly used as a catch-all server name.
    root /usr/share/nginx/html;    # This tells Nginx where the frontend files are located. 
    index index.html;              # This tells Nginx which file to serve when someone requests a directory or the root /.

    location / {                   
        try_files $uri $uri/ /index.html;  # Does the requested file (GET /style.css) and directory (/dashboard) exist? if no then server index.html.
    }

    location /api/ {                         # If the request starts with /api/, don't treat it as a frontend file. Send it to the backend.
        proxy_pass http://backend:5000;      # Docker Compose network allows containers to communicate using their service names. Reverse proxy works here. Nginx receives the API request and forwards it to the backend container on port 5000. 
        proxy_set_header Host $host;         # which host or domain name user asking? i want /api/status from example.com.
        proxy_set_header X-Real-IP $remote_addr;  # This passes the client's original IP address to the backend.
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # This keeps track of the original client IP through the proxy chain if there is multiple proxy or LB.
    }
}
